"""
Problem 2: Project Euler

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

Note: The Fibonacci sequence starts with 1, 2, ...
"""

limit = 4000000
result = 0

a, b = 1,2
while a <= limit:
    if a % 2 == 0:
        result += a
    a, b = b, a + b

print(result)

# *********

def even_fibonacci_numbers(limit):
    a, b = 1, 2
    while a <= limit:
        if a % 2 == 0:
            yield a
        a, b = b, a + b



limit = 4000000
result = sum(even_fibonacci_numbers(limit))

print(result)